In [1]:
import numpy as np
import xlearn as xl
from sklearn.datasets import load_wine
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Load dataset
wine_data = load_wine()
X = wine_data['data']
y = (wine_data['target'] == 1)

In [2]:
print(len(X[0]))

13


In [3]:
print(X)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]


In [4]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=0)

In [5]:
print(X_train)

[[1.369e+01 3.260e+00 2.540e+00 ... 9.600e-01 1.820e+00 6.800e+02]
 [1.269e+01 1.530e+00 2.260e+00 ... 9.600e-01 2.060e+00 4.950e+02]
 [1.162e+01 1.990e+00 2.280e+00 ... 1.160e+00 2.960e+00 3.450e+02]
 ...
 [1.242e+01 1.610e+00 2.190e+00 ... 1.060e+00 2.960e+00 3.450e+02]
 [1.390e+01 1.680e+00 2.120e+00 ... 9.100e-01 3.330e+00 9.850e+02]
 [1.416e+01 2.510e+00 2.480e+00 ... 6.200e-01 1.710e+00 6.600e+02]]


In [6]:
# Standardize input
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val)

In [7]:
print(X_train)

[[ 0.87668336  0.79842885  0.64412971 ...  0.0290166  -1.06412236
  -0.2059076 ]
 [-0.36659076 -0.7581304  -0.39779858 ...  0.0290166  -0.73083231
  -0.81704676]
 [-1.69689407 -0.34424759 -0.32337513 ...  0.90197362  0.51900537
  -1.31256499]
 ...
 [-0.70227477 -0.68615078 -0.65828065 ...  0.46549511  0.51900537
  -1.31256499]
 [ 1.13777093 -0.62316862 -0.91876272 ... -0.18922266  1.03282752
   0.80164614]
 [ 1.4610222   0.12361993  0.42085937 ... -1.45501034 -1.2168803
  -0.2719767 ]]


In [8]:
fm_model = xl.FMModel(task='binary', 
                      init=0.1, 
                      epoch=10, 
                      k=4, 
                      lr=0.1, 
                      reg_lambda=0.01, 
                      opt='sgd', 
                      metric='acc')
# Start to train
fm_model.fit(X_train, 
             y_train, 
             eval_set=[X_val, y_val])

# Generate predictions
y_pred = fm_model.predict(X_val)

In [46]:
for bias in fm_model.weights[0]:
    print(bias)

[      nan -0.739658]
[     nan -2.25234]
[     nan -1.07685]
[     nan -1.23442]
[    nan 0.83808]
[      nan -0.457781]
[      nan -0.137631]
[      nan 0.0763631]
[       nan 0.00716593]
[     nan 0.569307]
[     nan -2.19128]
[    nan 1.13712]
[     nan 0.473284]
[     nan -2.05791]


In [45]:
for column_w in fm_model.weights[1]:
    print(["{0:0.2f}".format(i) for i in column_w])

['nan', '0.00', '0.00', '0.01', '0.01']
['nan', '0.01', '0.01', '0.01', '0.01']
['nan', '0.00', '0.01', '0.00', '0.01']
['nan', '0.01', '0.01', '0.01', '0.01']
['nan', '0.01', '0.01', '0.01', '0.01']
['nan', '0.00', '0.00', '0.01', '0.01']
['nan', '0.01', '0.01', '0.00', '0.01']
['nan', '0.01', '0.01', '0.01', '0.01']
['nan', '0.00', '0.01', '0.00', '0.01']
['nan', '0.01', '0.01', '0.01', '0.00']
['nan', '0.01', '0.00', '0.01', '0.01']
['nan', '0.00', '0.01', '-0.00', '-0.00']
['nan', '0.00', '0.01', '0.00', '0.00']
